---
services:
  polishrr:
    image: ghcr.io/legromorph/polishrr:with-web
    container_name: polishrr
    environment:
      - CRON_SCHEDULE=0 * * * *
      - TZ=America/Los_Angeles
      - POLISHRR_TOKEN=<LONG_SECRET_TOKEN>
      # optional: IP-Allowlist (IPs or CIDRs)
      - ALLOWED_IPS=10.0.0.0/8,192.168.1.0/24
    volumes:
      - /path/to/config:/config # place your .env file in here
    user: "1000:1000"
    ports:
      - "8998:8998"
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:8998/healthz || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 20s
    restart: unless-stopped
      
